/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PaywallRouteImport } from './routes/paywall'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkoutIdRouteImport } from './routes/workout.$id'
import { Route as ApiCoachRouteImport } from './routes/api/coach'
import { Route as AdminOnboardingRouteImport } from './routes/admin.onboarding'
import { Route as AppWorkoutsRouteImport } from './routes/_app.workouts'
import { Route as AppTermsRouteImport } from './routes/_app.terms'
import { Route as AppProgressRouteImport } from './routes/_app.progress'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppPrivacyRouteImport } from './routes/_app.privacy'
import { Route as AppPhotosRouteImport } from './routes/_app.photos'
import { Route as AppNutritionRouteImport } from './routes/_app.nutrition'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppHomeRouteImport } from './routes/_app.home'
import { Route as AppHealthDisclaimerRouteImport } from './routes/_app.health-disclaimer'
import { Route as AppDeleteAccountRouteImport } from './routes/_app.delete-account'
import { Route as AppContactRouteImport } from './routes/_app.contact'
import { Route as AppCoachRouteImport } from './routes/_app.coach'
import { Route as WorkoutHistoryIndexRouteImport } from './routes/workout.history.index'
import { Route as AppScanIndexRouteImport } from './routes/_app.scan.index'
import { Route as AppReportIndexRouteImport } from './routes/_app.report.index'
import { Route as AppPhotosIndexRouteImport } from './routes/_app.photos.index'
import { Route as WorkoutHistoryIdRouteImport } from './routes/workout.history.$id'
import { Route as WorkoutIdSessionRouteImport } from './routes/workout.$id.session'
import { Route as AppReportHistoryRouteImport } from './routes/_app.report.history'
import { Route as AppReportWeekStartRouteImport } from './routes/_app.report.$weekStart'
import { Route as AppPhotosNewRouteImport } from './routes/_app.photos.new'
import { Route as AppPhotosCompareRouteImport } from './routes/_app.photos.compare'
import { Route as AppPhotosPhotoIdRouteImport } from './routes/_app.photos.$photoId'
import { Route as AppScanFaceIndexRouteImport } from './routes/_app.scan.face.index'
import { Route as AppScanBodyIndexRouteImport } from './routes/_app.scan.body.index'
import { Route as WorkoutIdDemoExerciseIdRouteImport } from './routes/workout.$id.demo.$exerciseId'
import { Route as ApiPublicHooksFinalizeWeeklyReportsRouteImport } from './routes/api/public/hooks/finalize-weekly-reports'
import { Route as AppScanFaceIdRouteImport } from './routes/_app.scan.face.$id'
import { Route as AppScanBodyNewRouteImport } from './routes/_app.scan.body.new'
import { Route as AppScanBodyIdRouteImport } from './routes/_app.scan.body.$id'

const PaywallRoute = PaywallRouteImport.update({
  id: '/paywall',
  path: '/paywall',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutIdRoute = WorkoutIdRouteImport.update({
  id: '/workout/$id',
  path: '/workout/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCoachRoute = ApiCoachRouteImport.update({
  id: '/api/coach',
  path: '/api/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOnboardingRoute = AdminOnboardingRouteImport.update({
  id: '/admin/onboarding',
  path: '/admin/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkoutsRoute = AppWorkoutsRouteImport.update({
  id: '/workouts',
  path: '/workouts',
  getParentRoute: () => AppRoute,
} as any)
const AppTermsRoute = AppTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => AppRoute,
} as any)
const AppProgressRoute = AppProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPrivacyRoute = AppPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => AppRoute,
} as any)
const AppPhotosRoute = AppPhotosRouteImport.update({
  id: '/photos',
  path: '/photos',
  getParentRoute: () => AppRoute,
} as any)
const AppNutritionRoute = AppNutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppHealthDisclaimerRoute = AppHealthDisclaimerRouteImport.update({
  id: '/health-disclaimer',
  path: '/health-disclaimer',
  getParentRoute: () => AppRoute,
} as any)
const AppDeleteAccountRoute = AppDeleteAccountRouteImport.update({
  id: '/delete-account',
  path: '/delete-account',
  getParentRoute: () => AppRoute,
} as any)
const AppContactRoute = AppContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AppRoute,
} as any)
const AppCoachRoute = AppCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => AppRoute,
} as any)
const WorkoutHistoryIndexRoute = WorkoutHistoryIndexRouteImport.update({
  id: '/workout/history/',
  path: '/workout/history/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppScanIndexRoute = AppScanIndexRouteImport.update({
  id: '/scan/',
  path: '/scan/',
  getParentRoute: () => AppRoute,
} as any)
const AppReportIndexRoute = AppReportIndexRouteImport.update({
  id: '/report/',
  path: '/report/',
  getParentRoute: () => AppRoute,
} as any)
const AppPhotosIndexRoute = AppPhotosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPhotosRoute,
} as any)
const WorkoutHistoryIdRoute = WorkoutHistoryIdRouteImport.update({
  id: '/workout/history/$id',
  path: '/workout/history/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutIdSessionRoute = WorkoutIdSessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => WorkoutIdRoute,
} as any)
const AppReportHistoryRoute = AppReportHistoryRouteImport.update({
  id: '/report/history',
  path: '/report/history',
  getParentRoute: () => AppRoute,
} as any)
const AppReportWeekStartRoute = AppReportWeekStartRouteImport.update({
  id: '/report/$weekStart',
  path: '/report/$weekStart',
  getParentRoute: () => AppRoute,
} as any)
const AppPhotosNewRoute = AppPhotosNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppPhotosRoute,
} as any)
const AppPhotosCompareRoute = AppPhotosCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => AppPhotosRoute,
} as any)
const AppPhotosPhotoIdRoute = AppPhotosPhotoIdRouteImport.update({
  id: '/$photoId',
  path: '/$photoId',
  getParentRoute: () => AppPhotosRoute,
} as any)
const AppScanFaceIndexRoute = AppScanFaceIndexRouteImport.update({
  id: '/scan/face/',
  path: '/scan/face/',
  getParentRoute: () => AppRoute,
} as any)
const AppScanBodyIndexRoute = AppScanBodyIndexRouteImport.update({
  id: '/scan/body/',
  path: '/scan/body/',
  getParentRoute: () => AppRoute,
} as any)
const WorkoutIdDemoExerciseIdRoute = WorkoutIdDemoExerciseIdRouteImport.update({
  id: '/demo/$exerciseId',
  path: '/demo/$exerciseId',
  getParentRoute: () => WorkoutIdRoute,
} as any)
const ApiPublicHooksFinalizeWeeklyReportsRoute =
  ApiPublicHooksFinalizeWeeklyReportsRouteImport.update({
    id: '/api/public/hooks/finalize-weekly-reports',
    path: '/api/public/hooks/finalize-weekly-reports',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppScanFaceIdRoute = AppScanFaceIdRouteImport.update({
  id: '/scan/face/$id',
  path: '/scan/face/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppScanBodyNewRoute = AppScanBodyNewRouteImport.update({
  id: '/scan/body/new',
  path: '/scan/body/new',
  getParentRoute: () => AppRoute,
} as any)
const AppScanBodyIdRoute = AppScanBodyIdRouteImport.update({
  id: '/scan/body/$id',
  path: '/scan/body/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/onboarding': typeof OnboardingRoute
  '/paywall': typeof PaywallRoute
  '/coach': typeof AppCoachRoute
  '/contact': typeof AppContactRoute
  '/delete-account': typeof AppDeleteAccountRoute
  '/health-disclaimer': typeof AppHealthDisclaimerRoute
  '/home': typeof AppHomeRoute
  '/notifications': typeof AppNotificationsRoute
  '/nutrition': typeof AppNutritionRoute
  '/photos': typeof AppPhotosRouteWithChildren
  '/privacy': typeof AppPrivacyRoute
  '/profile': typeof AppProfileRoute
  '/progress': typeof AppProgressRoute
  '/terms': typeof AppTermsRoute
  '/workouts': typeof AppWorkoutsRoute
  '/admin/onboarding': typeof AdminOnboardingRoute
  '/api/coach': typeof ApiCoachRoute
  '/workout/$id': typeof WorkoutIdRouteWithChildren
  '/photos/$photoId': typeof AppPhotosPhotoIdRoute
  '/photos/compare': typeof AppPhotosCompareRoute
  '/photos/new': typeof AppPhotosNewRoute
  '/report/$weekStart': typeof AppReportWeekStartRoute
  '/report/history': typeof AppReportHistoryRoute
  '/workout/$id/session': typeof WorkoutIdSessionRoute
  '/workout/history/$id': typeof WorkoutHistoryIdRoute
  '/photos/': typeof AppPhotosIndexRoute
  '/report/': typeof AppReportIndexRoute
  '/scan/': typeof AppScanIndexRoute
  '/workout/history/': typeof WorkoutHistoryIndexRoute
  '/scan/body/$id': typeof AppScanBodyIdRoute
  '/scan/body/new': typeof AppScanBodyNewRoute
  '/scan/face/$id': typeof AppScanFaceIdRoute
  '/api/public/hooks/finalize-weekly-reports': typeof ApiPublicHooksFinalizeWeeklyReportsRoute
  '/workout/$id/demo/$exerciseId': typeof WorkoutIdDemoExerciseIdRoute
  '/scan/body/': typeof AppScanBodyIndexRoute
  '/scan/face/': typeof AppScanFaceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/onboarding': typeof OnboardingRoute
  '/paywall': typeof PaywallRoute
  '/coach': typeof AppCoachRoute
  '/contact': typeof AppContactRoute
  '/delete-account': typeof AppDeleteAccountRoute
  '/health-disclaimer': typeof AppHealthDisclaimerRoute
  '/home': typeof AppHomeRoute
  '/notifications': typeof AppNotificationsRoute
  '/nutrition': typeof AppNutritionRoute
  '/privacy': typeof AppPrivacyRoute
  '/profile': typeof AppProfileRoute
  '/progress': typeof AppProgressRoute
  '/terms': typeof AppTermsRoute
  '/workouts': typeof AppWorkoutsRoute
  '/admin/onboarding': typeof AdminOnboardingRoute
  '/api/coach': typeof ApiCoachRoute
  '/workout/$id': typeof WorkoutIdRouteWithChildren
  '/photos/$photoId': typeof AppPhotosPhotoIdRoute
  '/photos/compare': typeof AppPhotosCompareRoute
  '/photos/new': typeof AppPhotosNewRoute
  '/report/$weekStart': typeof AppReportWeekStartRoute
  '/report/history': typeof AppReportHistoryRoute
  '/workout/$id/session': typeof WorkoutIdSessionRoute
  '/workout/history/$id': typeof WorkoutHistoryIdRoute
  '/photos': typeof AppPhotosIndexRoute
  '/report': typeof AppReportIndexRoute
  '/scan': typeof AppScanIndexRoute
  '/workout/history': typeof WorkoutHistoryIndexRoute
  '/scan/body/$id': typeof AppScanBodyIdRoute
  '/scan/body/new': typeof AppScanBodyNewRoute
  '/scan/face/$id': typeof AppScanFaceIdRoute
  '/api/public/hooks/finalize-weekly-reports': typeof ApiPublicHooksFinalizeWeeklyReportsRoute
  '/workout/$id/demo/$exerciseId': typeof WorkoutIdDemoExerciseIdRoute
  '/scan/body': typeof AppScanBodyIndexRoute
  '/scan/face': typeof AppScanFaceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/account': typeof AccountRoute
  '/onboarding': typeof OnboardingRoute
  '/paywall': typeof PaywallRoute
  '/_app/coach': typeof AppCoachRoute
  '/_app/contact': typeof AppContactRoute
  '/_app/delete-account': typeof AppDeleteAccountRoute
  '/_app/health-disclaimer': typeof AppHealthDisclaimerRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/nutrition': typeof AppNutritionRoute
  '/_app/photos': typeof AppPhotosRouteWithChildren
  '/_app/privacy': typeof AppPrivacyRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/progress': typeof AppProgressRoute
  '/_app/terms': typeof AppTermsRoute
  '/_app/workouts': typeof AppWorkoutsRoute
  '/admin/onboarding': typeof AdminOnboardingRoute
  '/api/coach': typeof ApiCoachRoute
  '/workout/$id': typeof WorkoutIdRouteWithChildren
  '/_app/photos/$photoId': typeof AppPhotosPhotoIdRoute
  '/_app/photos/compare': typeof AppPhotosCompareRoute
  '/_app/photos/new': typeof AppPhotosNewRoute
  '/_app/report/$weekStart': typeof AppReportWeekStartRoute
  '/_app/report/history': typeof AppReportHistoryRoute
  '/workout/$id/session': typeof WorkoutIdSessionRoute
  '/workout/history/$id': typeof WorkoutHistoryIdRoute
  '/_app/photos/': typeof AppPhotosIndexRoute
  '/_app/report/': typeof AppReportIndexRoute
  '/_app/scan/': typeof AppScanIndexRoute
  '/workout/history/': typeof WorkoutHistoryIndexRoute
  '/_app/scan/body/$id': typeof AppScanBodyIdRoute
  '/_app/scan/body/new': typeof AppScanBodyNewRoute
  '/_app/scan/face/$id': typeof AppScanFaceIdRoute
  '/api/public/hooks/finalize-weekly-reports': typeof ApiPublicHooksFinalizeWeeklyReportsRoute
  '/workout/$id/demo/$exerciseId': typeof WorkoutIdDemoExerciseIdRoute
  '/_app/scan/body/': typeof AppScanBodyIndexRoute
  '/_app/scan/face/': typeof AppScanFaceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/onboarding'
    | '/paywall'
    | '/coach'
    | '/contact'
    | '/delete-account'
    | '/health-disclaimer'
    | '/home'
    | '/notifications'
    | '/nutrition'
    | '/photos'
    | '/privacy'
    | '/profile'
    | '/progress'
    | '/terms'
    | '/workouts'
    | '/admin/onboarding'
    | '/api/coach'
    | '/workout/$id'
    | '/photos/$photoId'
    | '/photos/compare'
    | '/photos/new'
    | '/report/$weekStart'
    | '/report/history'
    | '/workout/$id/session'
    | '/workout/history/$id'
    | '/photos/'
    | '/report/'
    | '/scan/'
    | '/workout/history/'
    | '/scan/body/$id'
    | '/scan/body/new'
    | '/scan/face/$id'
    | '/api/public/hooks/finalize-weekly-reports'
    | '/workout/$id/demo/$exerciseId'
    | '/scan/body/'
    | '/scan/face/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/onboarding'
    | '/paywall'
    | '/coach'
    | '/contact'
    | '/delete-account'
    | '/health-disclaimer'
    | '/home'
    | '/notifications'
    | '/nutrition'
    | '/privacy'
    | '/profile'
    | '/progress'
    | '/terms'
    | '/workouts'
    | '/admin/onboarding'
    | '/api/coach'
    | '/workout/$id'
    | '/photos/$photoId'
    | '/photos/compare'
    | '/photos/new'
    | '/report/$weekStart'
    | '/report/history'
    | '/workout/$id/session'
    | '/workout/history/$id'
    | '/photos'
    | '/report'
    | '/scan'
    | '/workout/history'
    | '/scan/body/$id'
    | '/scan/body/new'
    | '/scan/face/$id'
    | '/api/public/hooks/finalize-weekly-reports'
    | '/workout/$id/demo/$exerciseId'
    | '/scan/body'
    | '/scan/face'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/account'
    | '/onboarding'
    | '/paywall'
    | '/_app/coach'
    | '/_app/contact'
    | '/_app/delete-account'
    | '/_app/health-disclaimer'
    | '/_app/home'
    | '/_app/notifications'
    | '/_app/nutrition'
    | '/_app/photos'
    | '/_app/privacy'
    | '/_app/profile'
    | '/_app/progress'
    | '/_app/terms'
    | '/_app/workouts'
    | '/admin/onboarding'
    | '/api/coach'
    | '/workout/$id'
    | '/_app/photos/$photoId'
    | '/_app/photos/compare'
    | '/_app/photos/new'
    | '/_app/report/$weekStart'
    | '/_app/report/history'
    | '/workout/$id/session'
    | '/workout/history/$id'
    | '/_app/photos/'
    | '/_app/report/'
    | '/_app/scan/'
    | '/workout/history/'
    | '/_app/scan/body/$id'
    | '/_app/scan/body/new'
    | '/_app/scan/face/$id'
    | '/api/public/hooks/finalize-weekly-reports'
    | '/workout/$id/demo/$exerciseId'
    | '/_app/scan/body/'
    | '/_app/scan/face/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AccountRoute: typeof AccountRoute
  OnboardingRoute: typeof OnboardingRoute
  PaywallRoute: typeof PaywallRoute
  AdminOnboardingRoute: typeof AdminOnboardingRoute
  ApiCoachRoute: typeof ApiCoachRoute
  WorkoutIdRoute: typeof WorkoutIdRouteWithChildren
  WorkoutHistoryIdRoute: typeof WorkoutHistoryIdRoute
  WorkoutHistoryIndexRoute: typeof WorkoutHistoryIndexRoute
  ApiPublicHooksFinalizeWeeklyReportsRoute: typeof ApiPublicHooksFinalizeWeeklyReportsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/paywall': {
      id: '/paywall'
      path: '/paywall'
      fullPath: '/paywall'
      preLoaderRoute: typeof PaywallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout/$id': {
      id: '/workout/$id'
      path: '/workout/$id'
      fullPath: '/workout/$id'
      preLoaderRoute: typeof WorkoutIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/coach': {
      id: '/api/coach'
      path: '/api/coach'
      fullPath: '/api/coach'
      preLoaderRoute: typeof ApiCoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/onboarding': {
      id: '/admin/onboarding'
      path: '/admin/onboarding'
      fullPath: '/admin/onboarding'
      preLoaderRoute: typeof AdminOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/workouts': {
      id: '/_app/workouts'
      path: '/workouts'
      fullPath: '/workouts'
      preLoaderRoute: typeof AppWorkoutsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/terms': {
      id: '/_app/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof AppTermsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/progress': {
      id: '/_app/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AppProgressRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/privacy': {
      id: '/_app/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof AppPrivacyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/photos': {
      id: '/_app/photos'
      path: '/photos'
      fullPath: '/photos'
      preLoaderRoute: typeof AppPhotosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/nutrition': {
      id: '/_app/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof AppNutritionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/health-disclaimer': {
      id: '/_app/health-disclaimer'
      path: '/health-disclaimer'
      fullPath: '/health-disclaimer'
      preLoaderRoute: typeof AppHealthDisclaimerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/delete-account': {
      id: '/_app/delete-account'
      path: '/delete-account'
      fullPath: '/delete-account'
      preLoaderRoute: typeof AppDeleteAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contact': {
      id: '/_app/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof AppContactRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/coach': {
      id: '/_app/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof AppCoachRouteImport
      parentRoute: typeof AppRoute
    }
    '/workout/history/': {
      id: '/workout/history/'
      path: '/workout/history'
      fullPath: '/workout/history/'
      preLoaderRoute: typeof WorkoutHistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/scan/': {
      id: '/_app/scan/'
      path: '/scan'
      fullPath: '/scan/'
      preLoaderRoute: typeof AppScanIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/report/': {
      id: '/_app/report/'
      path: '/report'
      fullPath: '/report/'
      preLoaderRoute: typeof AppReportIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/photos/': {
      id: '/_app/photos/'
      path: '/'
      fullPath: '/photos/'
      preLoaderRoute: typeof AppPhotosIndexRouteImport
      parentRoute: typeof AppPhotosRoute
    }
    '/workout/history/$id': {
      id: '/workout/history/$id'
      path: '/workout/history/$id'
      fullPath: '/workout/history/$id'
      preLoaderRoute: typeof WorkoutHistoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout/$id/session': {
      id: '/workout/$id/session'
      path: '/session'
      fullPath: '/workout/$id/session'
      preLoaderRoute: typeof WorkoutIdSessionRouteImport
      parentRoute: typeof WorkoutIdRoute
    }
    '/_app/report/history': {
      id: '/_app/report/history'
      path: '/report/history'
      fullPath: '/report/history'
      preLoaderRoute: typeof AppReportHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/report/$weekStart': {
      id: '/_app/report/$weekStart'
      path: '/report/$weekStart'
      fullPath: '/report/$weekStart'
      preLoaderRoute: typeof AppReportWeekStartRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/photos/new': {
      id: '/_app/photos/new'
      path: '/new'
      fullPath: '/photos/new'
      preLoaderRoute: typeof AppPhotosNewRouteImport
      parentRoute: typeof AppPhotosRoute
    }
    '/_app/photos/compare': {
      id: '/_app/photos/compare'
      path: '/compare'
      fullPath: '/photos/compare'
      preLoaderRoute: typeof AppPhotosCompareRouteImport
      parentRoute: typeof AppPhotosRoute
    }
    '/_app/photos/$photoId': {
      id: '/_app/photos/$photoId'
      path: '/$photoId'
      fullPath: '/photos/$photoId'
      preLoaderRoute: typeof AppPhotosPhotoIdRouteImport
      parentRoute: typeof AppPhotosRoute
    }
    '/_app/scan/face/': {
      id: '/_app/scan/face/'
      path: '/scan/face'
      fullPath: '/scan/face/'
      preLoaderRoute: typeof AppScanFaceIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scan/body/': {
      id: '/_app/scan/body/'
      path: '/scan/body'
      fullPath: '/scan/body/'
      preLoaderRoute: typeof AppScanBodyIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/workout/$id/demo/$exerciseId': {
      id: '/workout/$id/demo/$exerciseId'
      path: '/demo/$exerciseId'
      fullPath: '/workout/$id/demo/$exerciseId'
      preLoaderRoute: typeof WorkoutIdDemoExerciseIdRouteImport
      parentRoute: typeof WorkoutIdRoute
    }
    '/api/public/hooks/finalize-weekly-reports': {
      id: '/api/public/hooks/finalize-weekly-reports'
      path: '/api/public/hooks/finalize-weekly-reports'
      fullPath: '/api/public/hooks/finalize-weekly-reports'
      preLoaderRoute: typeof ApiPublicHooksFinalizeWeeklyReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/scan/face/$id': {
      id: '/_app/scan/face/$id'
      path: '/scan/face/$id'
      fullPath: '/scan/face/$id'
      preLoaderRoute: typeof AppScanFaceIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scan/body/new': {
      id: '/_app/scan/body/new'
      path: '/scan/body/new'
      fullPath: '/scan/body/new'
      preLoaderRoute: typeof AppScanBodyNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scan/body/$id': {
      id: '/_app/scan/body/$id'
      path: '/scan/body/$id'
      fullPath: '/scan/body/$id'
      preLoaderRoute: typeof AppScanBodyIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppPhotosRouteChildren {
  AppPhotosPhotoIdRoute: typeof AppPhotosPhotoIdRoute
  AppPhotosCompareRoute: typeof AppPhotosCompareRoute
  AppPhotosNewRoute: typeof AppPhotosNewRoute
  AppPhotosIndexRoute: typeof AppPhotosIndexRoute
}

const AppPhotosRouteChildren: AppPhotosRouteChildren = {
  AppPhotosPhotoIdRoute: AppPhotosPhotoIdRoute,
  AppPhotosCompareRoute: AppPhotosCompareRoute,
  AppPhotosNewRoute: AppPhotosNewRoute,
  AppPhotosIndexRoute: AppPhotosIndexRoute,
}

const AppPhotosRouteWithChildren = AppPhotosRoute._addFileChildren(
  AppPhotosRouteChildren,
)

interface AppRouteChildren {
  AppCoachRoute: typeof AppCoachRoute
  AppContactRoute: typeof AppContactRoute
  AppDeleteAccountRoute: typeof AppDeleteAccountRoute
  AppHealthDisclaimerRoute: typeof AppHealthDisclaimerRoute
  AppHomeRoute: typeof AppHomeRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppNutritionRoute: typeof AppNutritionRoute
  AppPhotosRoute: typeof AppPhotosRouteWithChildren
  AppPrivacyRoute: typeof AppPrivacyRoute
  AppProfileRoute: typeof AppProfileRoute
  AppProgressRoute: typeof AppProgressRoute
  AppTermsRoute: typeof AppTermsRoute
  AppWorkoutsRoute: typeof AppWorkoutsRoute
  AppReportWeekStartRoute: typeof AppReportWeekStartRoute
  AppReportHistoryRoute: typeof AppReportHistoryRoute
  AppReportIndexRoute: typeof AppReportIndexRoute
  AppScanIndexRoute: typeof AppScanIndexRoute
  AppScanBodyIdRoute: typeof AppScanBodyIdRoute
  AppScanBodyNewRoute: typeof AppScanBodyNewRoute
  AppScanFaceIdRoute: typeof AppScanFaceIdRoute
  AppScanBodyIndexRoute: typeof AppScanBodyIndexRoute
  AppScanFaceIndexRoute: typeof AppScanFaceIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCoachRoute: AppCoachRoute,
  AppContactRoute: AppContactRoute,
  AppDeleteAccountRoute: AppDeleteAccountRoute,
  AppHealthDisclaimerRoute: AppHealthDisclaimerRoute,
  AppHomeRoute: AppHomeRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppNutritionRoute: AppNutritionRoute,
  AppPhotosRoute: AppPhotosRouteWithChildren,
  AppPrivacyRoute: AppPrivacyRoute,
  AppProfileRoute: AppProfileRoute,
  AppProgressRoute: AppProgressRoute,
  AppTermsRoute: AppTermsRoute,
  AppWorkoutsRoute: AppWorkoutsRoute,
  AppReportWeekStartRoute: AppReportWeekStartRoute,
  AppReportHistoryRoute: AppReportHistoryRoute,
  AppReportIndexRoute: AppReportIndexRoute,
  AppScanIndexRoute: AppScanIndexRoute,
  AppScanBodyIdRoute: AppScanBodyIdRoute,
  AppScanBodyNewRoute: AppScanBodyNewRoute,
  AppScanFaceIdRoute: AppScanFaceIdRoute,
  AppScanBodyIndexRoute: AppScanBodyIndexRoute,
  AppScanFaceIndexRoute: AppScanFaceIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface WorkoutIdRouteChildren {
  WorkoutIdSessionRoute: typeof WorkoutIdSessionRoute
  WorkoutIdDemoExerciseIdRoute: typeof WorkoutIdDemoExerciseIdRoute
}

const WorkoutIdRouteChildren: WorkoutIdRouteChildren = {
  WorkoutIdSessionRoute: WorkoutIdSessionRoute,
  WorkoutIdDemoExerciseIdRoute: WorkoutIdDemoExerciseIdRoute,
}

const WorkoutIdRouteWithChildren = WorkoutIdRoute._addFileChildren(
  WorkoutIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AccountRoute: AccountRoute,
  OnboardingRoute: OnboardingRoute,
  PaywallRoute: PaywallRoute,
  AdminOnboardingRoute: AdminOnboardingRoute,
  ApiCoachRoute: ApiCoachRoute,
  WorkoutIdRoute: WorkoutIdRouteWithChildren,
  WorkoutHistoryIdRoute: WorkoutHistoryIdRoute,
  WorkoutHistoryIndexRoute: WorkoutHistoryIndexRoute,
  ApiPublicHooksFinalizeWeeklyReportsRoute:
    ApiPublicHooksFinalizeWeeklyReportsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
