/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PaywallRouteImport } from './routes/paywall'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkoutIdRouteImport } from './routes/workout.$id'
import { Route as ApiCoachRouteImport } from './routes/api/coach'
import { Route as AppWorkoutsRouteImport } from './routes/_app.workouts'
import { Route as AppProgressRouteImport } from './routes/_app.progress'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppNutritionRouteImport } from './routes/_app.nutrition'
import { Route as AppHomeRouteImport } from './routes/_app.home'
import { Route as AppCoachRouteImport } from './routes/_app.coach'
import { Route as WorkoutHistoryIndexRouteImport } from './routes/workout.history.index'
import { Route as AppScanIndexRouteImport } from './routes/_app.scan.index'
import { Route as WorkoutHistoryIdRouteImport } from './routes/workout.history.$id'
import { Route as WorkoutIdSessionRouteImport } from './routes/workout.$id.session'
import { Route as AppScanBodyIndexRouteImport } from './routes/_app.scan.body.index'
import { Route as WorkoutIdDemoExerciseIdRouteImport } from './routes/workout.$id.demo.$exerciseId'
import { Route as AppScanBodyNewRouteImport } from './routes/_app.scan.body.new'
import { Route as AppScanBodyIdRouteImport } from './routes/_app.scan.body.$id'

const PaywallRoute = PaywallRouteImport.update({
  id: '/paywall',
  path: '/paywall',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutIdRoute = WorkoutIdRouteImport.update({
  id: '/workout/$id',
  path: '/workout/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCoachRoute = ApiCoachRouteImport.update({
  id: '/api/coach',
  path: '/api/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkoutsRoute = AppWorkoutsRouteImport.update({
  id: '/workouts',
  path: '/workouts',
  getParentRoute: () => AppRoute,
} as any)
const AppProgressRoute = AppProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNutritionRoute = AppNutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppCoachRoute = AppCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => AppRoute,
} as any)
const WorkoutHistoryIndexRoute = WorkoutHistoryIndexRouteImport.update({
  id: '/workout/history/',
  path: '/workout/history/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppScanIndexRoute = AppScanIndexRouteImport.update({
  id: '/scan/',
  path: '/scan/',
  getParentRoute: () => AppRoute,
} as any)
const WorkoutHistoryIdRoute = WorkoutHistoryIdRouteImport.update({
  id: '/workout/history/$id',
  path: '/workout/history/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutIdSessionRoute = WorkoutIdSessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => WorkoutIdRoute,
} as any)
const AppScanBodyIndexRoute = AppScanBodyIndexRouteImport.update({
  id: '/scan/body/',
  path: '/scan/body/',
  getParentRoute: () => AppRoute,
} as any)
const WorkoutIdDemoExerciseIdRoute = WorkoutIdDemoExerciseIdRouteImport.update({
  id: '/demo/$exerciseId',
  path: '/demo/$exerciseId',
  getParentRoute: () => WorkoutIdRoute,
} as any)
const AppScanBodyNewRoute = AppScanBodyNewRouteImport.update({
  id: '/scan/body/new',
  path: '/scan/body/new',
  getParentRoute: () => AppRoute,
} as any)
const AppScanBodyIdRoute = AppScanBodyIdRouteImport.update({
  id: '/scan/body/$id',
  path: '/scan/body/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/paywall': typeof PaywallRoute
  '/coach': typeof AppCoachRoute
  '/home': typeof AppHomeRoute
  '/nutrition': typeof AppNutritionRoute
  '/profile': typeof AppProfileRoute
  '/progress': typeof AppProgressRoute
  '/workouts': typeof AppWorkoutsRoute
  '/api/coach': typeof ApiCoachRoute
  '/workout/$id': typeof WorkoutIdRouteWithChildren
  '/workout/$id/session': typeof WorkoutIdSessionRoute
  '/workout/history/$id': typeof WorkoutHistoryIdRoute
  '/scan/': typeof AppScanIndexRoute
  '/workout/history/': typeof WorkoutHistoryIndexRoute
  '/scan/body/$id': typeof AppScanBodyIdRoute
  '/scan/body/new': typeof AppScanBodyNewRoute
  '/workout/$id/demo/$exerciseId': typeof WorkoutIdDemoExerciseIdRoute
  '/scan/body/': typeof AppScanBodyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/paywall': typeof PaywallRoute
  '/coach': typeof AppCoachRoute
  '/home': typeof AppHomeRoute
  '/nutrition': typeof AppNutritionRoute
  '/profile': typeof AppProfileRoute
  '/progress': typeof AppProgressRoute
  '/workouts': typeof AppWorkoutsRoute
  '/api/coach': typeof ApiCoachRoute
  '/workout/$id': typeof WorkoutIdRouteWithChildren
  '/workout/$id/session': typeof WorkoutIdSessionRoute
  '/workout/history/$id': typeof WorkoutHistoryIdRoute
  '/scan': typeof AppScanIndexRoute
  '/workout/history': typeof WorkoutHistoryIndexRoute
  '/scan/body/$id': typeof AppScanBodyIdRoute
  '/scan/body/new': typeof AppScanBodyNewRoute
  '/workout/$id/demo/$exerciseId': typeof WorkoutIdDemoExerciseIdRoute
  '/scan/body': typeof AppScanBodyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/paywall': typeof PaywallRoute
  '/_app/coach': typeof AppCoachRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/nutrition': typeof AppNutritionRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/progress': typeof AppProgressRoute
  '/_app/workouts': typeof AppWorkoutsRoute
  '/api/coach': typeof ApiCoachRoute
  '/workout/$id': typeof WorkoutIdRouteWithChildren
  '/workout/$id/session': typeof WorkoutIdSessionRoute
  '/workout/history/$id': typeof WorkoutHistoryIdRoute
  '/_app/scan/': typeof AppScanIndexRoute
  '/workout/history/': typeof WorkoutHistoryIndexRoute
  '/_app/scan/body/$id': typeof AppScanBodyIdRoute
  '/_app/scan/body/new': typeof AppScanBodyNewRoute
  '/workout/$id/demo/$exerciseId': typeof WorkoutIdDemoExerciseIdRoute
  '/_app/scan/body/': typeof AppScanBodyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/paywall'
    | '/coach'
    | '/home'
    | '/nutrition'
    | '/profile'
    | '/progress'
    | '/workouts'
    | '/api/coach'
    | '/workout/$id'
    | '/workout/$id/session'
    | '/workout/history/$id'
    | '/scan/'
    | '/workout/history/'
    | '/scan/body/$id'
    | '/scan/body/new'
    | '/workout/$id/demo/$exerciseId'
    | '/scan/body/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/paywall'
    | '/coach'
    | '/home'
    | '/nutrition'
    | '/profile'
    | '/progress'
    | '/workouts'
    | '/api/coach'
    | '/workout/$id'
    | '/workout/$id/session'
    | '/workout/history/$id'
    | '/scan'
    | '/workout/history'
    | '/scan/body/$id'
    | '/scan/body/new'
    | '/workout/$id/demo/$exerciseId'
    | '/scan/body'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/onboarding'
    | '/paywall'
    | '/_app/coach'
    | '/_app/home'
    | '/_app/nutrition'
    | '/_app/profile'
    | '/_app/progress'
    | '/_app/workouts'
    | '/api/coach'
    | '/workout/$id'
    | '/workout/$id/session'
    | '/workout/history/$id'
    | '/_app/scan/'
    | '/workout/history/'
    | '/_app/scan/body/$id'
    | '/_app/scan/body/new'
    | '/workout/$id/demo/$exerciseId'
    | '/_app/scan/body/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  PaywallRoute: typeof PaywallRoute
  ApiCoachRoute: typeof ApiCoachRoute
  WorkoutIdRoute: typeof WorkoutIdRouteWithChildren
  WorkoutHistoryIdRoute: typeof WorkoutHistoryIdRoute
  WorkoutHistoryIndexRoute: typeof WorkoutHistoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/paywall': {
      id: '/paywall'
      path: '/paywall'
      fullPath: '/paywall'
      preLoaderRoute: typeof PaywallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout/$id': {
      id: '/workout/$id'
      path: '/workout/$id'
      fullPath: '/workout/$id'
      preLoaderRoute: typeof WorkoutIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/coach': {
      id: '/api/coach'
      path: '/api/coach'
      fullPath: '/api/coach'
      preLoaderRoute: typeof ApiCoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/workouts': {
      id: '/_app/workouts'
      path: '/workouts'
      fullPath: '/workouts'
      preLoaderRoute: typeof AppWorkoutsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/progress': {
      id: '/_app/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AppProgressRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/nutrition': {
      id: '/_app/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof AppNutritionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/coach': {
      id: '/_app/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof AppCoachRouteImport
      parentRoute: typeof AppRoute
    }
    '/workout/history/': {
      id: '/workout/history/'
      path: '/workout/history'
      fullPath: '/workout/history/'
      preLoaderRoute: typeof WorkoutHistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/scan/': {
      id: '/_app/scan/'
      path: '/scan'
      fullPath: '/scan/'
      preLoaderRoute: typeof AppScanIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/workout/history/$id': {
      id: '/workout/history/$id'
      path: '/workout/history/$id'
      fullPath: '/workout/history/$id'
      preLoaderRoute: typeof WorkoutHistoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout/$id/session': {
      id: '/workout/$id/session'
      path: '/session'
      fullPath: '/workout/$id/session'
      preLoaderRoute: typeof WorkoutIdSessionRouteImport
      parentRoute: typeof WorkoutIdRoute
    }
    '/_app/scan/body/': {
      id: '/_app/scan/body/'
      path: '/scan/body'
      fullPath: '/scan/body/'
      preLoaderRoute: typeof AppScanBodyIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/workout/$id/demo/$exerciseId': {
      id: '/workout/$id/demo/$exerciseId'
      path: '/demo/$exerciseId'
      fullPath: '/workout/$id/demo/$exerciseId'
      preLoaderRoute: typeof WorkoutIdDemoExerciseIdRouteImport
      parentRoute: typeof WorkoutIdRoute
    }
    '/_app/scan/body/new': {
      id: '/_app/scan/body/new'
      path: '/scan/body/new'
      fullPath: '/scan/body/new'
      preLoaderRoute: typeof AppScanBodyNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scan/body/$id': {
      id: '/_app/scan/body/$id'
      path: '/scan/body/$id'
      fullPath: '/scan/body/$id'
      preLoaderRoute: typeof AppScanBodyIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCoachRoute: typeof AppCoachRoute
  AppHomeRoute: typeof AppHomeRoute
  AppNutritionRoute: typeof AppNutritionRoute
  AppProfileRoute: typeof AppProfileRoute
  AppProgressRoute: typeof AppProgressRoute
  AppWorkoutsRoute: typeof AppWorkoutsRoute
  AppScanIndexRoute: typeof AppScanIndexRoute
  AppScanBodyIdRoute: typeof AppScanBodyIdRoute
  AppScanBodyNewRoute: typeof AppScanBodyNewRoute
  AppScanBodyIndexRoute: typeof AppScanBodyIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCoachRoute: AppCoachRoute,
  AppHomeRoute: AppHomeRoute,
  AppNutritionRoute: AppNutritionRoute,
  AppProfileRoute: AppProfileRoute,
  AppProgressRoute: AppProgressRoute,
  AppWorkoutsRoute: AppWorkoutsRoute,
  AppScanIndexRoute: AppScanIndexRoute,
  AppScanBodyIdRoute: AppScanBodyIdRoute,
  AppScanBodyNewRoute: AppScanBodyNewRoute,
  AppScanBodyIndexRoute: AppScanBodyIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface WorkoutIdRouteChildren {
  WorkoutIdSessionRoute: typeof WorkoutIdSessionRoute
  WorkoutIdDemoExerciseIdRoute: typeof WorkoutIdDemoExerciseIdRoute
}

const WorkoutIdRouteChildren: WorkoutIdRouteChildren = {
  WorkoutIdSessionRoute: WorkoutIdSessionRoute,
  WorkoutIdDemoExerciseIdRoute: WorkoutIdDemoExerciseIdRoute,
}

const WorkoutIdRouteWithChildren = WorkoutIdRoute._addFileChildren(
  WorkoutIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  PaywallRoute: PaywallRoute,
  ApiCoachRoute: ApiCoachRoute,
  WorkoutIdRoute: WorkoutIdRouteWithChildren,
  WorkoutHistoryIdRoute: WorkoutHistoryIdRoute,
  WorkoutHistoryIndexRoute: WorkoutHistoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
