/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkoutIdRouteImport } from './routes/workout.$id'
import { Route as AppWorkoutsRouteImport } from './routes/_app.workouts'
import { Route as AppProgressRouteImport } from './routes/_app.progress'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppNutritionRouteImport } from './routes/_app.nutrition'
import { Route as AppHomeRouteImport } from './routes/_app.home'
import { Route as AppScanIndexRouteImport } from './routes/_app.scan.index'
import { Route as AppScanBodyIndexRouteImport } from './routes/_app.scan.body.index'
import { Route as AppScanBodyNewRouteImport } from './routes/_app.scan.body.new'
import { Route as AppScanBodyIdRouteImport } from './routes/_app.scan.body.$id'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutIdRoute = WorkoutIdRouteImport.update({
  id: '/workout/$id',
  path: '/workout/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkoutsRoute = AppWorkoutsRouteImport.update({
  id: '/workouts',
  path: '/workouts',
  getParentRoute: () => AppRoute,
} as any)
const AppProgressRoute = AppProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNutritionRoute = AppNutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppScanIndexRoute = AppScanIndexRouteImport.update({
  id: '/scan/',
  path: '/scan/',
  getParentRoute: () => AppRoute,
} as any)
const AppScanBodyIndexRoute = AppScanBodyIndexRouteImport.update({
  id: '/scan/body/',
  path: '/scan/body/',
  getParentRoute: () => AppRoute,
} as any)
const AppScanBodyNewRoute = AppScanBodyNewRouteImport.update({
  id: '/scan/body/new',
  path: '/scan/body/new',
  getParentRoute: () => AppRoute,
} as any)
const AppScanBodyIdRoute = AppScanBodyIdRouteImport.update({
  id: '/scan/body/$id',
  path: '/scan/body/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/home': typeof AppHomeRoute
  '/nutrition': typeof AppNutritionRoute
  '/profile': typeof AppProfileRoute
  '/progress': typeof AppProgressRoute
  '/workouts': typeof AppWorkoutsRoute
  '/workout/$id': typeof WorkoutIdRoute
  '/scan/': typeof AppScanIndexRoute
  '/scan/body/$id': typeof AppScanBodyIdRoute
  '/scan/body/new': typeof AppScanBodyNewRoute
  '/scan/body/': typeof AppScanBodyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/home': typeof AppHomeRoute
  '/nutrition': typeof AppNutritionRoute
  '/profile': typeof AppProfileRoute
  '/progress': typeof AppProgressRoute
  '/workouts': typeof AppWorkoutsRoute
  '/workout/$id': typeof WorkoutIdRoute
  '/scan': typeof AppScanIndexRoute
  '/scan/body/$id': typeof AppScanBodyIdRoute
  '/scan/body/new': typeof AppScanBodyNewRoute
  '/scan/body': typeof AppScanBodyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/nutrition': typeof AppNutritionRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/progress': typeof AppProgressRoute
  '/_app/workouts': typeof AppWorkoutsRoute
  '/workout/$id': typeof WorkoutIdRoute
  '/_app/scan/': typeof AppScanIndexRoute
  '/_app/scan/body/$id': typeof AppScanBodyIdRoute
  '/_app/scan/body/new': typeof AppScanBodyNewRoute
  '/_app/scan/body/': typeof AppScanBodyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/home'
    | '/nutrition'
    | '/profile'
    | '/progress'
    | '/workouts'
    | '/workout/$id'
    | '/scan/'
    | '/scan/body/$id'
    | '/scan/body/new'
    | '/scan/body/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/home'
    | '/nutrition'
    | '/profile'
    | '/progress'
    | '/workouts'
    | '/workout/$id'
    | '/scan'
    | '/scan/body/$id'
    | '/scan/body/new'
    | '/scan/body'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/onboarding'
    | '/_app/home'
    | '/_app/nutrition'
    | '/_app/profile'
    | '/_app/progress'
    | '/_app/workouts'
    | '/workout/$id'
    | '/_app/scan/'
    | '/_app/scan/body/$id'
    | '/_app/scan/body/new'
    | '/_app/scan/body/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  WorkoutIdRoute: typeof WorkoutIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout/$id': {
      id: '/workout/$id'
      path: '/workout/$id'
      fullPath: '/workout/$id'
      preLoaderRoute: typeof WorkoutIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/workouts': {
      id: '/_app/workouts'
      path: '/workouts'
      fullPath: '/workouts'
      preLoaderRoute: typeof AppWorkoutsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/progress': {
      id: '/_app/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AppProgressRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/nutrition': {
      id: '/_app/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof AppNutritionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scan/': {
      id: '/_app/scan/'
      path: '/scan'
      fullPath: '/scan/'
      preLoaderRoute: typeof AppScanIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scan/body/': {
      id: '/_app/scan/body/'
      path: '/scan/body'
      fullPath: '/scan/body/'
      preLoaderRoute: typeof AppScanBodyIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scan/body/new': {
      id: '/_app/scan/body/new'
      path: '/scan/body/new'
      fullPath: '/scan/body/new'
      preLoaderRoute: typeof AppScanBodyNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scan/body/$id': {
      id: '/_app/scan/body/$id'
      path: '/scan/body/$id'
      fullPath: '/scan/body/$id'
      preLoaderRoute: typeof AppScanBodyIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppHomeRoute: typeof AppHomeRoute
  AppNutritionRoute: typeof AppNutritionRoute
  AppProfileRoute: typeof AppProfileRoute
  AppProgressRoute: typeof AppProgressRoute
  AppWorkoutsRoute: typeof AppWorkoutsRoute
  AppScanIndexRoute: typeof AppScanIndexRoute
  AppScanBodyIdRoute: typeof AppScanBodyIdRoute
  AppScanBodyNewRoute: typeof AppScanBodyNewRoute
  AppScanBodyIndexRoute: typeof AppScanBodyIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppHomeRoute: AppHomeRoute,
  AppNutritionRoute: AppNutritionRoute,
  AppProfileRoute: AppProfileRoute,
  AppProgressRoute: AppProgressRoute,
  AppWorkoutsRoute: AppWorkoutsRoute,
  AppScanIndexRoute: AppScanIndexRoute,
  AppScanBodyIdRoute: AppScanBodyIdRoute,
  AppScanBodyNewRoute: AppScanBodyNewRoute,
  AppScanBodyIndexRoute: AppScanBodyIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  WorkoutIdRoute: WorkoutIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
